language: python
python:
  - "2.7"

before_install:
  # Docker
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce

  # CF
  - wget https://clis.ng.bluemix.net/download/bluemix-cli/latest/linux64 -O /tmp/bluemix_cli.tar.gz
  - tar xvf /tmp/bluemix_cli.tar.gz
  - sudo ./Bluemix_CLI/install_bluemix_cli


script:
  # Automated Tests (unit, integration, etc)
  - python tests.py

deploy:
  - provider: script
    skip_cleanup: true
    script: ./deploy.sh
    on:
      branch: master
      type: push